version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      aws-sdk:
        patterns: ["github.com/aws/*"]

  - package-ecosystem: gomod
    directory: /ssh-cert-api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      aws-sdk:
        patterns: ["github.com/aws/*"]

  - package-ecosystem: gomod
    directory: /ssh-cert-signer
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      aws-sdk:
        patterns: ["github.com/aws/*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
